# Generated by Django 6.0.5 on 2026-06-02 00:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('estudiante', 'Estudiante'), ('profesor', 'Profesor')], default='estudiante', max_length=15),
        ),
        migrations.CreateModel(
            name='SolicitudProfesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=255)),
                ('dni', models.CharField(max_length=30)),
                ('pais', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=50)),
                ('institucion', models.CharField(max_length=255)),
                ('especialidad', models.CharField(max_length=255)),
                ('motivo_contacto', models.CharField(default='Verificación de rol profesor', max_length=255)),
                ('certificado_titulo', models.FileField(upload_to='verificaciones/titulos/')),
                ('dni_frente', models.ImageField(upload_to='verificaciones/dni/')),
                ('dni_dorso', models.ImageField(upload_to='verificaciones/dni/')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_profesor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
