# Generated by Django 6.0.5 on 2026-06-02 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_usuario_rol_solicitudprofesor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudprofesor',
            name='direccion',
        ),
    ]
