# Generated by Django 6.0.5 on 2026-06-02 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_solicitudprofesor_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudprofesor',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='solicitudprofesor',
            name='provincia',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
