# Generated by Django 6.0.5 on 2026-06-03 09:29
# Generated by Django 6.0.5 on 2026-06-02 19:48


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_solicitudprofesor_ciudad_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examen',
            options={'verbose_name_plural': 'Examenes'},
        ),
        migrations.AlterModelOptions(
            name='intentoexamen',
            options={'verbose_name_plural': 'Intentos de Examenes'},
        ),
        migrations.AlterModelOptions(
            name='nivel',
            options={'verbose_name_plural': 'Niveles'},
        ),
        migrations.AlterModelOptions(
            name='opcion',
            options={'verbose_name_plural': 'Opciones'},
        ),
        migrations.AlterModelOptions(
            name='profesor',
            options={'verbose_name_plural': 'Profesores'},
        ),
        migrations.AlterModelOptions(
            name='respuestausuario',
            options={'verbose_name_plural': 'Respuestas de Usuarios'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name_plural': 'Usuarios'},
        ),
    ]
