# Generated by Django 6.0.5 on 2026-06-03 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_examen_options_alter_intentoexamen_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudprofesor',
            name='ciudad',
        ),
    ]
