# Generated by Django 6.0.4 on 2026-09-15 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_solicitudprofesor_ciudad'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profesor',
        ),
    ]
