# Generated by Django 6.0.4 on 2026-09-15 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_delete_profesor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestConnection',
        ),
    ]
